### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by sunjianyou** [ikergarcia1996/Self-Driving-Car-in-Video-Games#4]
when i run with V3 use small_V3 there is an error.
my environment
python 3.7.6
cuda 10.2
numpy 1.16
pytorch 1.6.0
error:
Traceback (most recent call last):
  File "D:/learn/code/Self-Driving-Car-in-Video-Games-master (1)/Self-Driving-Car-in-Video-Games-master/run_TEDD1104.py", line 143, in run_ted1104
    model_prediction: torch.tensor = model.predict(X).cpu().numpy()
  File "D:\learn\code\Self-Driving-Car-in-Video-Games-master (1)\Self-Driving-Car-in-Video-Games-master\model.py", line 337, in predict
    x = self.EncoderRNN.predict(x)
  File "D:\learn\code\Self-Driving-Car-in-Video-Games-master (1)\Self-Driving-Car-in-Video-Games-master\model.py", line 181, in predict
    output, (h_n, c_n) = self.lstm(features)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 577, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

**Comment by sunjianyou** [comment]
i reinstall apex and its ok
